# Step 1: Build using Maven
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Step 2: Run the app
FROM eclipse-temurin:17-jdk

WORKDIR /app
COPY --from=build /app/target/vehicle-rental-backend-1.0.0.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]