# Step 1: Build
FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Step 2: Run
FROM eclipse-temurin:21-jdk

WORKDIR /app
COPY --from=build /app/target/vehicle-rental-backend-1.0.0.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]