spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_rental
spring.datasource.username=postgres
spring.datasource.password=Dhanuuh_07
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=vehicleRentalSecretKey2024VeryLongSecretKeyForJWTSigning
jwt.expiration=86400000

server.port=8080
spring.web.cors.allowed-origins=http://localhost:3000
